CUDA_VISIBLE_DEVICES=1 accelerate launch finetune_instruct_pix2pix_dpo.py \
  --pretrained_model_name_or_path="/home/luca_piai/big_disk/ip2p_fine_tune_mvtec_7" \
  --train_data_dir="/home/luca_piai/big_disk/datasets/dpo_train_images" \
  --output_dir="/home/luca_piai/big_disk/ip2p_dpo_mvtec_7_style1/" \
  --resolution=512 \
  --train_batch_size=8 --gradient_accumulation_steps=2 \
  --dataloader_num_workers=16 \
  --learning_rate=1e-7 \
  --center_crop \
  --random_flip \
  --max_train_steps=750 \
  --checkpointing_steps=250 \
  --val_image_url="/home/luca_piai/big_disk/datasets/mvtec/pill/test/good/000.png" \
  --validation_prompt="<retain red dots> a pill with a chipped edge" \
  --validation_epochs=8 \
  --num_validation_images=4 \
  --mixed_precision="bf16" \
  --allow_tf32 \
  --torch_compile \
  --report_to="wandb" \
  --seed=42 \